// Player-facing event and gameplay translations.
public static partial class LocalizationTable
{
    private static void AddGameplay()
    {
        Add("임시 상납소", "Temporary Tribute Office");
        Add("피난 안내도의 화살표가 전부 이곳을 가리키고 있었다. 접수구 위에 적힌 글씨 — “상납은 질서다.”", "Every arrow on the evacuation map pointed here. Above the counter: “Tribute is order.”");
        Add("영혼석을 바친다", "Offer Soulstones");
        Add("“이상하리만큼 마음이 편해졌다. 그게 제일 이상했다.”", "“An uncanny calm settled over us. That was the strangest part.”");
        Add("접수구를 뒤진다", "Search the counter");
        Add("“앞사람의 상납분이다. 장부에는 이미 ‘수령 완료’라고 적혀 있었다.”", "“The previous visitor's tribute. The ledger already marked it as received.”");
        Add("“접수구 안쪽에서, 손이 아닌 것이 손목을 잡았다.”", "“Something that was not a hand seized a wrist from inside the counter.”");
        Add("무시한다", "Ignore it");
        Add("낯익은 조사관", "A Familiar Investigator");
        Add("벽에 기대앉은 조사관. 장비도, 소속 배지도 당신과 같다. 이름표만 비어 있다.", "An investigator sits against the wall. Their equipment and badge match yours. Only the name tag is blank.");
        Add("부축한다", "Help them up");
        Add("“고맙다는 말 대신, 그는 당신의 이름을 정확히 불렀다.”", "“Instead of thanking you, he called you by your exact name.”");
        Add("말을 건다", "Speak to them");
        Add("“그는 말없이 일어나 당신들 뒤에 섰다.”", "“He rose without a word and stood behind your group.”");
        Add("“빈 이름표가 바닥에 떨어졌다. 안쪽에 당신의 이름이 적혀 있었다.”", "“The blank name tag fell to the floor. Your name was written inside.”");
        Add("지나친다", "Pass by");
        Add("“뒤에서 발소리가 따라오다, 멈췄다.”", "“Footsteps followed behind you, then stopped.”");
        Add("속삭이는 영혼석", "Whispering Soulstone");
        Add("회수 규격을 벗어난 크기의 영혼석. 귀를 대지 않아도 들린다. 당신의 목소리로 말하고 있다.", "A Soulstone larger than recovery regulations allow. You hear it without leaning closer. It speaks in your voice.");
        Add("귀를 기울인다", "Listen closely");
        Add("“싸우는 법을 알려주었다. 그것이 어떻게 아는지는 말하지 않았다.”", "“It told us how to fight. It did not explain how it knew.”");
        Add("규격대로 회수한다", "Recover it by protocol");
        Add("“쪼개는 순간, 목소리는 비명 없이 끝났다.”", "“As it split, the voice ended without a scream.”");
        Add("부순다", "Smash it");
        Add("“잠깐, 세계가 조용해졌다.”", "“For a moment, the world fell silent.”");
        Add("임시 브리핑 단말", "Temporary Briefing Terminal");
        Add("“복귀 전 브리핑을 수강하십시오.” 화면 속 진행자는 눈을 깜빡이지 않는다.", "“Please attend a briefing before returning.” The presenter on the screen does not blink.");
        Add("수강한다", "Attend the briefing");
        Add("“머리가 맑아졌다. 무언가를 잊은 대가라는 생각도, 곧 잊었다.”", "“Our minds cleared. We soon forgot the thought that we had forgotten something in exchange.”");
        Add("단말을 뜯어본다", "Dismantle the terminal");
        Add("“전임자의 미수령 수당이 나왔다. 수령인 서명란은 비어 있었다.”", "“A predecessor's unclaimed allowance emerged. The recipient's signature was blank.”");
        Add("“‘무단 접근이 기록되었습니다.’ 어디에 기록되는지는 적혀 있지 않았다.”", "“Unauthorized access recorded. It did not say where.”");
        Add("전원을 끈다", "Turn it off");
        Add("“꺼진 화면에 비친 당신은, 한 박자 늦게 움직였다.”", "“Your reflection in the dark screen moved a beat too late.”");
        Add("거울 복도", "Hall of Mirrors");
        Add("양쪽 벽이 거울이다. 거울 속 일행은 숫자가 맞는데, 한 명은 지금과 다른 표정을 하고 있다.", "Mirrors line both walls. The reflected party has the right number of people, but one wears a different expression.");
        Add("다른 표정을 들여다본다", "Examine the odd reflection");
        Add("“거울 속의 그가 먼저 눈을 돌렸다. 지금의 그는, 조금 다른 사람 같다.”", "“His reflection looked away first. He seems a little different now.”");
        Add("거울을 깬다", "Break the mirror");
        Add("“깨진 조각들은 전부 바닥만 비추었다. 그편이 나았다.”", "“Every broken shard reflected only the floor. That was better.”");
        Add("“조각이 튀었다. 거울 안쪽에서.”", "“Shards flew out. From inside the mirror.”");
        Add("시선을 내리고 통과한다", "Look down and walk through");
        Add("봉인된 보급 상자", "Sealed Supply Crate");
        Add("탐사국 보급 상자. 로고가 낯익은데, 볼수록 눈이 미끄러진다. 잠금 장치는 이쪽을 향해 달려 있다.", "A Bureau supply crate. The logo seems familiar, but your eyes slip off it the longer you look. The lock faces you.");
        Add("규정 해제 코드를 시도한다", "Try the standard unlock code");
        Add("“코드가 맞았다. 당신이 이 코드를 어떻게 알고 있었는지는, 넘어가자.”", "“The code worked. Let us not ask how you knew it.”");
        Add("“‘권한 없음.’ 상자가 조금 더 단단해진 것 같다.”", "“Access denied. The crate seems a little sturdier now.”");
        Add("강제로 연다", "Force it open");
        Add("“경첩이 아니라 이빨이 부러지는 소리가 났다.”", "“The sound was teeth breaking, not hinges.”");
        Add("놓아둔다", "Leave it alone");
        Add("지켜보는 까마귀", "The Watching Raven");
        Add("까마귀 한 마리가 앉아 있다. 날개 소리를 들은 기억이 없다. 처음부터 거기 있었던 것처럼.", "A raven perches nearby. You do not remember hearing wings. As if it had been there all along.");
        Add("먹이를 준다", "Offer food");
        Add("“까마귀는 먹이를 먹지 않았다. 다만 세는 것을 멈추었다.”", "“The raven did not eat. It merely stopped counting.”");
        Add("쫓아낸다", "Drive it away");
        Add("“그것은 웃는 것처럼 울었다.”", "“Its cry sounded like laughter.”");
        Add("마주 본다", "Meet its gaze");
        Add("“까마귀의 눈에 낫이 비쳤다. 이 방에는 낫이 없다.”", "“A scythe reflected in its eyes. There is no scythe in this room.”");
        Add("“먼저 눈을 돌린 쪽은 당신이었다.”", "“You were the first to look away.”");
        Add("뒤처진 자의 잔재", "Remains of the Left Behind");
        Add("바닥에 희미하게 빛나는 잔상이 놓여 있다. 전투에서 행동하지 못하고 사라진 동료의 잔재다. 만지면 아직 따뜻하다.", "A faintly glowing afterimage lies on the floor. The remnant of a companion who vanished without acting in battle. Still warm to the touch.");
        Add("잔재를 흡수한다", "Absorb the remnant");
        Add("“잔재가 녹아든 순간, 모두의 표정이 잠시 굳었다. 그걸 본 모두의 표정이.”", "“As the remnant dissolved into us, every face briefly stiffened. Every face that saw it.”");
        Add("“잔상을 밟고 지나간다. 발밑에서 무언가 가볍게 부서지는 느낌이 들었다.”", "“We stepped over the afterimage. Something seemed to crumble lightly underfoot.”");
        Add("영혼석 공명", "Soulstone Resonance");
        Add("주머니 속 영혼석이 갑자기 진동한다. 공명이 동료들의 형체를 일그러뜨리고 있다. 구현체들이 고통스러운 듯 몸을 움츠린다.", "The Soulstones in your pocket suddenly vibrate. Their resonance distorts your companions' forms. The manifestations hunch as if in pain.");
        Add("공명을 증폭시킨다", "Amplify the resonance");
        Add("“동료의 형체가 잠시 흐려졌다가 되돌아온다. 그 사이로 무언가 더 단단한 것이 엿보였다.”", "“A companion's shape blurred and returned. Something harder showed through in between.”");
        Add("동료들에게 분산시킨다", "Disperse it among companions");
        Add("“공명이 퍼져나간 자리에, 낯선 형체 하나가 어렴풋이 서 있었다. 아는 얼굴 같기도 하다.”", "“Where the resonance spread, an unfamiliar figure stood faintly. The face almost seemed familiar.”");
        Add("영혼석을 감춘다", "Conceal the Soulstones");
        Add("“돌을 천으로 감싸자 진동이 멎었다. 동료들이 안도한 듯 보인다. 정말일까.”", "“Wrapped in cloth, the stones stopped vibrating. Our companions look relieved. Are they?”");
        Add("벽에 새겨진 눈금", "Marks on the Wall");
        Add("복도 막다른 벽에 손톱으로 긁은 눈금이 빽빽하다. 마흔일곱 개. 마지막 몇 줄은 피가 섞여 있다. 손바닥을 대보자 홈의 간격이 네 손가락과 정확히 일치한다.", "Forty-seven nail-scratched marks cover the dead-end wall. Blood stains the last few. Against your palm, the grooves match your four fingers exactly.");
        Add("마지막 눈금을 긋는다", "Carve the last mark");
        Add("“마흔여덟째를 새긴다. 손끝에 전해지는 감촉이 낯설지 않다.”", "“We carved the forty-eighth. The feeling at our fingertips was not unfamiliar.”");
        Add("“마흔여덟째를 긋는다. 동료들이 한 걸음 물러선다.”", "“We carved the forty-eighth. Our companions stepped back.”");
        Add("흔적을 통째로 긁어 지운다", "Scrape away every mark");
        Add("“숫자가 사라진다. 모두가 안심한 표정이다. 나만 왠지 손끝이 허전하다.”", "“The number vanished. Everyone looked relieved. Only my fingertips felt strangely empty.”");
        Add("격리 해제 승인서", "Quarantine Release Approval");
        Add("바닥에 흩어진 서류 더미. 탐사국 발신 「격리 해제 승인서」다. 피험자 번호, 체액 채취 동의, 재배치 가능 일자… 모든 항목에 도장이 찍혀 있다. 서명란에는 내 이름이 있다. 기억나지 않는다.", "Bureau quarantine release forms lie scattered. Subject number, fluid sampling consent, redeployment date... Every item is stamped. My name is signed. I do not remember.");
        Add("서류를 챙긴다", "Take the documents");
        Add("“주머니에 접어 넣는다. 문구 하나가 눈에 박힌다. ‘피험자는 절차에 동의하였으며, 기억 소거는 표준 규정에 따른 것임.’”", "“I folded them into my pocket. One line stayed with me: The subject consented; memory erasure followed standard protocol.”");
        Add("찢어 버린다", "Tear them up");
        Add("“찢는다. 또 찢는다. 종이 조각이 흩어진다. 동료가 묻는다. ‘뭐였어?’ 대답하지 않는다. 목구멍까지 올라온 말을 삼킨다.”", "“I tore them, then tore them again. Scraps scattered. A companion asked what they were. I swallowed my answer.”");
        Add("두 개의 진입 기록", "Two Entry Records");
        Add("벽면에 부착된 구형 탐사 일지. 오늘자, 이 구역 진입 기록이 두 건이다. 한 건은 06:12, 내 서명. 다른 한 건은 03:47, 역시 내 서명. 새벽의 나는 혼자 와 있었다.", "An old field log hangs on the wall. Two entries for this area today: 06:12, my signature. 03:47, also mine. Before dawn, I came alone.");
        Add("03:47 기록을 뜯어낸다", "Remove the 03:47 entry");
        Add("“종이를 뜯어 주머니에 넣는다. 손이 떨린다. 내 서명은 분명한데, 내 기억은 아니다.”", "“I tore out the page and pocketed it. My hands trembled. The signature was mine. The memory was not.”");
        Add("기록을 정독한다", "Read the log closely");
        Add("“기록에 따르면 나는 뭔가를 ‘회수’했다. 회수물 란은 비어 있다. 공란의 잉크 색이 주변보다 진하다. 누군가 지운 흔적이다.”", "“The log says I recovered something. The recovered item field is blank, with darker ink than its surroundings. Someone erased it.”");
        Add("그 자리", "That Spot");
        Add("좁은 통로를 빠져나가던 중, 동료 한 명이 갑자기 멈춰 선다. 허공을 응시한다. 입술이 움직이지만 소리는 없다. 몇 초 후 아무 일 없었다는 듯 걷기 시작한다.", "In a narrow passage, a companion suddenly stops. They stare into empty air, lips moving silently. Seconds later, they walk on as if nothing happened.");
        Add("“괜찮아?” 묻는다", "Ask if they are all right");
        Add("“돌아본다. 미소를 짓는다. 방금 멈춰 섰던 자리를 정확히 피해서 걸어간다. 본인은 눈치채지 못했다.”", "“They turned and smiled, then walked precisely around the spot where they had stopped. They did not notice.”");
        Add("손목을 잡는다", "Grasp their wrist");
        Add("“움켜쥐자 동공이 한순간 풀린다. 이내 초점이 돌아온다. ‘미안, 잠깐 멍했어.’ 손목은 차갑다. 오래된 돌을 쥔 것 같다.”", "“Their pupils unfocused, then returned. Sorry, I spaced out. Their wrist was cold, like an old stone.”");
        Add("잊힌 봉납 제단", "Forgotten Offering Altar");
        Add("돌 제단 위, 말라붙은 핏자국이 영혼석 몇 점과 나란히 놓여 있다. 누군가 바치고 갔는지, 바치려다 도망쳤는지는 알 수 없다.", "Dried blood lies beside a few Soulstones on a stone altar. You cannot tell whether someone made an offering or fled before doing so.");
        Add("피를 바친다", "Offer blood");
        Add("“상처가 아물지 않는다. 대신 손안의 돌이 체온을 빨아들이듯 따뜻해진다.”", "“The wound would not close. Instead, the stone in my hand warmed as if drawing out my body heat.”");
        Add("“돌이 제단에 닿자 바스러진다. 동시에 상처가 거짓말처럼 사라진다. 다만, 기분 좋은 일은 아니다.”", "“The stones crumbled on the altar. Our wounds vanished like a lie. It was not a pleasant feeling.”");
        Add("“당연한 거래처럼 보였다. 그게 더 신경 쓰인다.”", "“It looked like an ordinary exchange. That troubled me more.”");
        Add("갈라진 틈새의 손", "A Hand in the Rift");
        Add("복도 벽에 난 균열, 그 틈새로 사람의 손이 뻗어 나와 있다. 손바닥을 위로 향한 채, 무언가를 기다리는 자세다.", "A human hand reaches through a crack in the corridor wall. Palm up, waiting for something.");
        Add("손을 잡는다", "Take the hand");
        Add("“손이 부드럽게 돌을 쥐여주고 틈새 너머로 사라진다. 손바닥에 남은 온기. 사람 체온이다.”", "“The hand gently gave us stones and vanished through the rift. Human warmth lingered on our palms.”");
        Add("“손이 움켜잡는다. 손목을 타고 올라온 한기가 머릿속 어딘가를 만진다. 놓아도, 만져진 기억은 남는다.”", "“The hand gripped tight. Cold climbed my wrist and touched something in my mind. The memory of that touch remained after release.”");
        Add("“손은 아직 기다리고 있다.”", "“The hand is still waiting.”");
        Add("기생하는 빛", "Parasitic Light");
        Add("어둠 속에 한 점 빛이 떠 있다. 가까이 다가가자 빛이 파티원들의 그림자를 훑더니, 가장 희미한 그림자 앞에서 멈춘다.", "A point of light floats in the dark. As you approach, it scans the party's shadows and stops before the faintest one.");
        Add("빛을 받아들인다", "Accept the light");
        Add("“빛이 당신들을 비추더니 이내 만족한 듯 사라진다. 바닥에 영혼석 한 줌이 남았다.”", "“The light shone on us, then vanished as if satisfied. A handful of Soulstones remained.”");
        Add("밀쳐낸다", "Push it away");
        Add("“빛은 한 번 깜빡이더니 소리 없이 꺼졌다. 눈을 깜빡일 때마다 각막 뒤에서 무엇이 남아 움직이는 기분이다.”", "“The light flickered once and silently died. With each blink, something still seems to move behind my eyes.”");
        Add("“빛은 여전히 가장 약한 그림자를 응시하고 있다. 아니, 그냥 빛일 뿐이다.”", "“The light still watches the weakest shadow. No. It is only light.”");
        Add("언덕의 보물상자", "Chest on the Hill");
        Add("목적지로 향하던 중, 언덕 한 구석에 커다란 보물상자가 놓여 있는 것을 발견한다. 주변에는 누군가 버리고 간 듯한 부서진 방패와 부러진 창대가 널브러져 있다 — 버려진 것치고는, 상자를 지키듯 둘러서 있다.", "On the way to your destination, a large chest stands on a hillside. Broken shields and spear shafts lie around it, arranged almost as if guarding it.");
        Add("상자를 열어본다", "Open the chest");
        Add("“상자 안에는 언제부터 방치됐는지 모를 시체들이 뒤엉켜 있었다. 구역질을 참으며 뒤진 끝에, 당신은 그것을 꺼냈다. 시체들은 전부, 빈손이었다.”", "“Bodies lay tangled inside, abandoned for who knows how long. Fighting nausea, you searched and took it out. Every corpse was empty-handed.”");
        Add("무시하고 지나간다", "Ignore it and move on");
        Add("“상자는 언덕에 남았다. 뒤돌아봤을 때, 뚜껑이 조금 더 열려 있었다.”", "“The chest remained on the hill. Looking back, its lid had opened a little farther.”");
        Add("발신불명의 메시지", "Message from an Unknown Sender");
        Add("조사 노트에 정체불명의 좌표가 스스로 기록되고 있다. 좌표가 가리키는 지점은, 지금 있는 곳에서 그리 멀지 않다.", "Unknown coordinates write themselves in your notebook. They point somewhere not far from here.");
        Add("좌표를 따라간다", "Follow the coordinates");
        Add("“숲길을 헤치고 나온 당신 앞에, 동료와 똑같이 생긴 존재가 목을 매단 채 죽어 있다. 널브러진 소지품에서 영혼석을 챙겼다. 노트의 좌표는, 다음 줄을 적기 시작했다.”", "“Beyond the forest path, a being identical to your companion hangs dead. You take Soulstones from its belongings. The notebook begins another line of coordinates.”");
        Add("갈 길을 서두른다", "Hurry onward");
        Add("“궁금증을 눌러두고 발걸음을 재촉했다. 그날 밤, 노트의 좌표는 지워져 있었다. 잉크 자국도 없이.”", "“We suppressed our curiosity and hurried on. That night, the coordinates had vanished without even an ink stain.”");
        Add("화면을 누르거나 확인 키를 눌러 계속", "Tap the screen or press Confirm to continue");
        Add("확인하면 타이틀로 돌아갑니다", "Confirm to return to the title");
        Add("확인하면 현장으로 이동합니다", "Confirm to enter the field");
        Add("{0}명을 더 선택해주세요", "Select {0} more companions");
        Add("같은 성급의 동료 3명을 선택해주세요", "Select 3 companions of the same star tier");
        Add("합성 준비 완료", "Ready to fuse");
        Add("파티 인원: {0}/{1}", "Party: {0}/{1}");
        Add("리롤 ({0})", "Reroll ({0})");
        Add("예비대 ({0}/{1})", "Reserves ({0}/{1})");
        Add("슬롯 {0} — {1} 동료만 선택 가능", "Slot {0} — {1} companions only");
        Add("슬롯 {0} 에 넣을 동료 선택", "Select a companion for slot {0}");
        Add("동료 명단", "Companion Roster");
        Add("회복할 동료가 없습니다.", "No companions to heal.");
        Add("휴식 완료 — {0}명에게 HP +{1} / 스트레스 -{2}", "Rest complete — {0} companions: HP +{1} / Stress -{2}");
        Add("패시브 잠금", "Passive Locked");
        Add("자폭 {0}턴", "Detonates in {0} turns");
        Add("자폭!", "Detonate!");
        Add("변화 없음.", "No change.");
        Add("(영혼석 {0} 필요)", "(Requires {0} Soulstones)");
        Add("까마귀", "Raven");
        Add("매 턴 도트 피해", "Damage over time each turn");
        Add("스킬 위력 -10% / 받는 스트레스 +10%", "Skill power -10% / Stress received +10%");
        Add("행동 불가 또는 코스트 증가", "Cannot act or increased skill cost");
        Add("이번 턴 행동 불가", "Cannot act this turn");
        Add("다음 턴 스킬 코스트 +1", "Skill cost +1 next turn");
        Add("역할별 약화 (전투 종료까지)", "Role-specific penalty until battle ends");
        Add("이 적을 우선 공격", "Prioritize this enemy");
        Add("{0}  ({1}턴 남음)", "{0}  ({1} turns remaining)");
        Add("강화", "Buff");
        Add("약화", "Debuff");
        Add("공격+실드", "Attack + Shield");
        Add("공격+도발", "Attack + Taunt");
        Add("단일 적", "One Enemy");
        Add("광역 적", "All Enemies");
        Add("단일 아군", "One Ally");
        Add("전체 아군", "All Allies");
        Add("아군 지원", "Ally Support");
        Add("자신", "Self");
        Add("불러오는 중", "Loading");
        Add("영혼석이 부족합니다 (필요 {0})", "Not enough Soulstones ({0} required)");
        Add("파티와 예비대가 가득 찼습니다", "Party and reserves are full");
        Add("(파티 없음)", "(No party)");
        Add("턴 {0}", "Turn {0}");
        Add("턴 종료 시 랜덤으로 {0}개의 카드가 파괴됩니다.", "At turn end, {0} random cards will be destroyed.");
        Add("전장의 방패", "War Shield");
        Add("적 전체에 20 데미지(분산) + 아군 전체에 30 실드 부여.", "Deal 20 damage distributed among all enemies and grant all allies 30 Shield.");
        Add("워크라이", "War Cry");
        Add("적 전체에 20 데미지(분산) + 시전자에게 1턴 도발. 도발 불가 적은 데미지만 적용.", "Deal 20 damage distributed among all enemies and grant the caster Taunt for 1 turn. Taunt-immune enemies only take damage.");
        Add("발도", "Draw Strike");
        Add("적 1명에게 25의 데미지를 입힌다.", "Deal 25 damage to one enemy.");
        Add("파이어볼", "Fireball");
        Add("모든 적에게 35의 데미지를 입힌다.", "Deal 35 damage to all enemies.");
        Add("일섬", "Flash Strike");
        Add("적 1명에게 50의 강력한 데미지를 입힌다.", "Deal a powerful 50 damage to one enemy.");
        Add("매직 미사일", "Magic Missile");
        Add("적 1명에게 15의 데미지를 입힌다.", "Deal 15 damage to one enemy.");
        Add("전투 태세", "Battle Stance");
        Add("아군 전체에게 40의 실드를 부여한다.", "Grant all allies 40 Shield.");
        Add("방어 준비", "Guard");
        Add("아군 전체에게 20의 실드를 부여한다.", "Grant all allies 20 Shield.");
        Add("불굴", "Indomitable");
        Add("아군 전체의 HP를 34 회복한다.", "Restore 34 HP to all allies.");
        Add("무모한 강타", "Reckless Strike");
        Add("적 1명에게 15의 데미지를 입힌다.", "Deal 15 damage to one enemy.");
        Add("기원", "Prayer");
        Add("아군 전체의 HP를 40 회복한다.", "Restore 40 HP to all allies.");
        Add("별부름", "Star Call");
        Add("HP가 가장 낮은 아군 1명의 HP를 35 회복한다.", "Restore 35 HP to the ally with the lowest HP.");
        Add("매직 실드", "Magic Shield");
        Add("아군 1명에게 20의 실드를 부여한다.", "Grant one ally 20 Shield.");
        Add("아이스스톰", "Ice Storm");
        Add("모든 적에게 55의 데미지를 입힌다.", "Deal 55 damage to all enemies.");
        Add("하늘가르기", "Sky Slash");
        Add("적 1명에게 75의 강력한 데미지를 입힌다.", "Deal a powerful 75 damage to one enemy.");
        Add("월광베기", "Moonlight Slash");
        Add("적 1명에게 60의 데미지를 입힌다.", "Deal 60 damage to one enemy.");
        Add("방패 밀치기", "Shield Bash");
        Add("적 1명에게 15의 데미지를 입힌다.", "Deal 15 damage to one enemy.");
        Add("역류", "Counterflow");
        Add("모든 적에게 25의 데미지를 입힌다.", "Deal 25 damage to all enemies.");
        Add("축성", "Consecration");
        Add("아군 1명의 HP를 12 회복한다.", "Restore 12 HP to one ally.");
        Add("심판", "Judgment");
        Add("적 1명에게 35의 신성 데미지를 입힌다.", "Deal 35 holy damage to one enemy.");
        Add("단검 휘두르기", "Dagger Slash");
        Add("전열 1번 아군에게 15 데미지.", "Deal 15 damage to the first ally in the front row.");
        Add("독침 쏘기", "Poison Dart");
        Add("후열 마지막 아군에게 30 데미지. 다음 2턴 동안 매 턴 10 도트 피해.", "Deal 30 damage to the last ally in the back row, then 10 damage each turn for 2 turns.");
        Add("도끼 휘두르기", "Axe Swing");
        Add("전열 1번에게 20 데미지. HP 30% 초과 시 발동.", "Deal 20 damage to the first ally in the front row. Activates above 30% HP.");
        Add("도끼 던지기", "Axe Throw");
        Add("전열 1번에게 60 데미지. HP 30% 이하 시 1회 강제 발동.", "Deal 60 damage to the first ally in the front row. Forced once at 30% HP or below.");
        Add("휘두르기", "Sweep");
        Add("전열 1, 2번에게 동시에 각 30 데미지.", "Deal 30 damage each to the first two allies in the front row.");
        Add("까마귀 부름", "Call Ravens");
        Add("까마귀 2마리 소환. 2회 피격 시 처치되며 3턴간 생존, 만료 시 1마리당 40 데미지를 파티에 분산한다. 3턴 쿨다운.", "Summon 2 ravens. Each dies after 2 hits or lasts 3 turns. On expiry, each deals 40 damage distributed across the party. Cooldown: 3 turns.");
        Add("수확", "Harvest");
        Add("HP 50% 이하 시 1회 강제. 각 아군에게 50 데미지. 실드가 먼저 흡수하고, 실드 초과분 합계만큼 보스 HP를 회복한다.", "Forced once at 50% HP or below. Deal 50 damage to each ally. Shields absorb damage first; the boss heals for the total damage beyond the shields.");
        Add("순간이동", "Teleport");
        Add("파티 배치 순서를 역순으로 뒤집는다. 까마귀 부름 실패 후 다음 보스 턴에 발동.", "Reverse the party formation. Activates on the next boss turn after Call Ravens fails.");
        Add("전투 준비 중", "Preparing for battle");
        Add("용병소 — 고용", "Mercenary Office — Hire");
        Add("용병소 — 판매", "Mercenary Office — Sell");
        Add("용병소 — 방출", "Mercenary Office — Release");
        Add("파티 편성 — 교체", "Party Formation — Swap");
        Add("교회 — 회복 기도", "Church — Healing Prayer");
        Add("교회 — 안정 기도", "Church — Calming Prayer");
        Add("교회 — 부활", "Church — Revive");
        Add("화톳불 정비", "Campfire Rest");
        Add("파티 합류", "Joined the party");
        Add("예비대 보관", "Added to reserves");
        Add("영혼석 -{0} → 보유 {1}", "Soulstones -{0} → Balance {1}");
        Add("영혼석 +{0} → 보유 {1}", "Soulstones +{0} → Balance {1}");
        Add("{0} 스트레스 -{1} → {2}", "{0} Stress -{1} → {2}");
        Add("{0} 부활 ({1}★, HP {2})", "{0} revived ({1}★, HP {2})");
        Add("{0} 예비대 → 파티 합류", "{0}: Reserves → Party");
        Add("{0} 파티 → 예비대 보관", "{0}: Party → Reserves");
        Add("{0} ↔ {1} 교체", "Swapped {0} ↔ {1}");
        Add("{0} ({1} | {2}★) 방출 (환급 없음)", "{0} ({1} | {2}★) released (no refund)");
        Add("{0} ({1} | {2}★) 판매", "{0} ({1} | {2}★) sold");
        Add("지원하지 않는 기능입니다", "This action is unavailable");
        Add("경직", "Frozen");
        Add("중증", "Severe Debuff");
        Add("이름", "Name");
        Add("가격", "Price");
        Add("예비대", "Reserves");
        Add("스택", "Stack");
        Add("턴", "Turn");
        Add("기사", "Knight");
        Add("라인하르트", "Reinhardt");
        Add("스킬1", "Skill 1");
        Add("영혼석", "Soulstones");
        Add("스트레스", "Stress");
        Add("합성", "Fusion");
        Add("동료 성장", "Companion Fusion");
        Add("3명을 선택해주세요", "Select 3 companions");
        Add("동료 모집", "Recruit Companions");
        Add("동료 명단 보기", "View Companion Roster");
        Add("전투 효과음", "Battle SFX");
        Add("스킵", "Skip");
        Add("잠시 후 새로운 탐사가 시작됩니다…", "A new expedition will begin shortly...");
        Add("보스 처치\n\n엔딩", "Boss Defeated\n\nThe End");
        Add("종료", "Exit");
        Add("지원", "Support");
        Add("공격", "Attack");
        Add("방어", "Defense");
        Add("+{0} 영혼석 환급", "Refunded {0} Soulstones");
        Add("원거리", "Ranged");
        Add("근접", "Melee");
        Add("받는 피해 +30%", "Damage taken +30%");
        Add("부여 실드 -50%", "Shield granted -50%");
        Add("광역 회복 → 단일 회복", "Area healing → Single-target healing");
        Add("없음", "None");
        Add("{0}이(가) 공포에 질려 행동하지 못한다.", "{0} is frozen in fear and cannot act.");
        Add("{0}이(가) [{1}]을(를) 사용했다!", "{0} used [{1}]!");
        Add("{0}이(가) 행동하지 않아 다음 턴 스택 +1 (행동 우선)", "{0} did not act: Stack +1 next turn (Action Priority)");
        Add("수호 결속 — {0}가 피해 {1} 분담.", "Guardian Bond — {0} shares {1} damage.");
        Add("{0}의 실드가 {1}을(를) 흡수!", "{0}'s Shield absorbed {1}!");
        Add("{0}이(가) {1}의 피해를 입었다!", "{0} took {1} damage!");
        Add("{0}의 스트레스 +{1} ({2}/100)", "{0} Stress +{1} ({2}/100)");
        Add("{0} 중증 디버프 — {1} (전투 종료까지).", "{0}: Severe Debuff — {1} (until battle ends).");
        Add("{0}이(가) 패닉! 공포 경직 발동.", "{0} panics! Frozen in fear.");
        Add("{0}이(가) 과호흡! 다음 턴 스킬 코스트 +1.", "{0} hyperventilates! Skill cost +1 next turn.");
        Add("탈진! 살아있는 동료 전원 스트레스 +{0}.", "Exhaustion! All living companions: Stress +{0}.");
        Add("{0}이(가) 쓰러졌다.", "{0} has fallen.");
        Add("{0}의 스트레스 +20 (동료 사망)", "{0} Stress +20 (companion death)");
        Add("{0} 처치! 영혼석 +{1}", "{0} defeated! Soulstones +{1}");
        Add("{0}이(가) 보스와 함께 사라졌다.", "{0} vanished with the boss.");
        Add("{0}에게 {1} 실드.", "{0} gains {1} Shield.");
        Add("{0}이(가) {1}마리 적을 {2}턴 도발!", "{0} taunts {1} enemies for {2} turns!");
        Add("비전 연쇄! {0}에게 추가 타격 (+{1})", "Arcane Chain! Extra hit on {0} (+{1})");
        Add("피의 갈망 — {0} HP +{1}.", "Bloodlust — {0} HP +{1}.");
        Add("{0} 처치!", "{0} defeated!");
        Add("{0}의 HP +{1} 회복.", "{0} recovers {1} HP.");
        Add("정화의 빛 — {0} 스트레스 -{1}.", "Purifying Light — {0} Stress -{1}.");
        Add("수호 기도 — {0} 실드 +{1}.", "Guardian Prayer — {0} Shield +{1}.");
        Add("{0}의 실드 +{1}.", "{0} Shield +{1}.");
        Add("전투 승리!", "Victory!");
        Add("다시 도전!", "Try again!");
        Add("전투에서 승리했다!", "Battle won!");
        Add("보스를 쓰러트렸다!", "Boss defeated!");
        Add("전원 쓰러졌다…", "Everyone has fallen...");
        Add("생존한 동료들의 스트레스가 회복되었다 (-10).", "Living companions recovered Stress (-10).");
        Add("{0}이(가) {1}을(를) 공격!", "{0} attacks {1}!");
        Add("{0}이(가) 중독되었다! ({1}×{2}턴)", "{0} is poisoned! ({1} damage × {2} turns)");
        Add("{0}이(가) 등장!", "{0} appears!");
        Add("{0} 만료! 각 아군에게 {1}의 피해.", "{0} expires! Each ally takes {1} damage.");
        Add("{0}이(가) {1}의 HP를 흡수!", "{0} absorbs {1} HP!");
        Add("{0}이(가) 진형을 뒤바꿨다!", "{0} reversed the formation!");
        Add("영혼석 부족 (필요 {0}).", "Not enough Soulstones ({0} required).");
        Add("교회 기도 — {0}명 HP +{1} (총 +{2}, 영혼석 -{3}).", "Church prayer — {0} companions: HP +{1} (total +{2}, Soulstones -{3}).");
        Add("스트레스를 풀어줄 동료가 없습니다.", "No companions need Stress relief.");
        Add("교회 기도 — {0}명 스트레스 -{1} (총 -{2}, 영혼석 -{3}).", "Church prayer — {0} companions: Stress -{1} (total -{2}, Soulstones -{3}).");
        Add("영혼석 부족 — {0} 부활 (필요 {1}).", "Not enough Soulstones to revive {0} ({1} required).");
        Add("부활 실패 — 파티 빈 슬롯이 없습니다.", "Revival failed — no free party slots.");
        Add("{0} 부활! ({1}★, 영혼석 -{2})", "{0} revived! ({1}★, Soulstones -{2})");
        Add("동료 사망으로 손패 카드 1장이 파괴되었다.", "A companion's death destroyed 1 card in hand.");
        Add("영혼석 -{0}", "Soulstones -{0}");
        Add("암시 텍스트를 얻었다.", "A clue was found.");
        Add("{0}명 스트레스 {1}{2}", "{0} companions: Stress {1}{2}");
        Add("{0}명 HP {1}{2}", "{0} companions: HP {1}{2}");
        Add("{0}명 HP -{1} (사망 없음)", "{0} companions: HP -{1} (nonlethal)");
        Add("{0}명 스트레스 +{1}", "{0} companions: Stress +{1}");
        Add("언어", "Language");
        Add("동료 합류 효과는 아직 사용할 수 없습니다.", "Companion recruitment effects are not available yet.");
        Add("다음 전투 스택 선지급 효과는 아직 사용할 수 없습니다.", "Next-battle Stack bonuses are not available yet.");
        Add("성향 재굴림 효과는 아직 사용할 수 없습니다.", "Affinity rerolls are not available yet.");
        Add("오브제 획득 효과는 아직 사용할 수 없습니다.", "Object acquisition is not available yet.");
        Add("오염도 변경 효과는 아직 사용할 수 없습니다.", "Corruption changes are not available yet.");
    }
}
